- hosts: all
  vars:
  user: cstark
  home: /home/cstark
- hosts: all
  vars_files:
  - vars/users.yml

vars:
user: joe
tasks:
# This line will read: Creates the user joe
- name: Creates the user {{ user }}
user:
# This line will create the user named Joe
name: "{{ user }}"


#users.yml
user: joe
home: /home/joe
